### ISSUE TITLE
Can not create a GitBackup repository on ThingWorx 9.0

### ISSUE THREAD

**Issue by vrosu** [PTCInc/thingworx-gitbackup-extension#1]
As of now, the latest 3.0.1 GitBackup Extension, if you try to create a GitBackup repository will fail.
**Cause:** the lifecycle methods changed their signature in the ThingWorx 9.0 Extension SDK. Some lifecycle methods are used in the GitBackup Extension, and as a result of the signature change, they will no longer execute in ThingWorx 9.0.
**Status:**  A GitBackup version will be released specifically for ThingWorx 9.0 in the following days.

**Comment by mpalladi** [comment]
Look forward to this. It would be useful to add a tooltip over the Bitbucket/other selector. For our use case we host Bitbucket internally and without looking at the user manual it's not possibe to know this is Online BB only

**Comment by vrosu** [comment]
Thanks for providing this feedback, that modification is easy to do. As a quick sneak peak, the following version will have the capability to export specific entities, and will further remove some internal xml attributes that will ensure the diff is cleaner.

**Comment by vrosu** [comment]
@mpalladi Version 4.0.0 was released yesterday and it includes the modification you suggested above.
Take care if you use it in 9.0, because that is a separate release.
Due to the early nature of a x.0.0 release, please test it first in a duplicated repository
