### ISSUE TITLE
Extension import does not work on ThingWorx 9.0

### ISSUE THREAD

**Issue by voiladaniel** [PTCInc/thingworx-gitbackup-extension#10]
Hello,

I am trying to install this TWX extension but unfortunately it give me an error message and when I check the ApplicationLog I see no error/warn.

Should I install any other extension or something on the server before I install GitBackup Extension?

Any idea what to check?

Thanks in advance!

![image](https://user-images.githubusercontent.com/53874653/96885467-4aa0e480-148b-11eb-9975-3afaf8873aa5.png)

**Comment by vrosu** [comment]
Nope, you don't need anything before installing it.
Question 1: what ThingWorx version are you using?
Question 2: have you tried installing any other Java-based extension (like the MQTT or Mail Extensions)?

**Comment by voiladaniel** [comment]
1. I am using ThingWorx 9.0.0-b9557
2. I just tried to install MQTT and Mail Extensions and it worked.

PS: GitBackup extension doesn't even work to validate it.

**Comment by vrosu** [comment]
I'm really not sure why it would both not want to install, and neither log something in the ApplicationLog.
Try the following:
-unzip the extension pack - you should have around 5 or 6 extensions
-install each extension manually, with GitBackupExtension being the last

**Comment by voiladaniel** [comment]
> I'm really not sure why it would both not want to install, and neither log something in the ApplicationLog.
> Try the following:
> -unzip the extension pack - you should have around 5 or 6 extensions
> -install each extension manually, with GitBackupExtension being the last

All works except GitBackupExtension.
I also got the logs from the others but not for GitBackupExtension.

**Comment by voiladaniel** [comment]
@vrosu many thanks for your help!

I manage to find out what was the problem. 
The solution that fixed the problem was to **increase "client_max_body_size" in nginx** config.
