### ISSUE TITLE
config file getting locked

### ISSUE THREAD

**Issue by srijithkrishnan1** [PTCInc/thingworx-gitbackup-extension#20]
Error observed with Git things within ThingWorx, things stop running and giving an error 'Things[<thingName>] is not running'.

Noticed an error in logs mentioning  GitRepository/<folderName>/.git/config file is locked, once the locked config file is deleted from ThingworxStorage/repository/GitRepository/<repoName>/.git/ and the instance is restarted the issue gets fixed temporarily. 
Unable to find the root cause.

**Comment by cbadici** [comment]
Hi @srijithkrishnan1 , 
Could you please provide more details about this error? 
First of all, what version of the Git extension and ThingWorx are you using? 
Secondly, what steps have you performed before you have reached this error? 
Thanks. 

Costin

**Comment by cbadici** [comment]
closed due to lack of response
