### ISSUE TITLE
Entities are not getting Pushed in Git.

### ISSUE THREAD

**Issue by anitas4** [PTCInc/thingworx-gitbackup-extension#21]
If i Push the entities it'll only getting pushed in File Repository and not in Git Repository. Thingworx version -9

**Comment by cbadici** [comment]
Hi, 
Could you please provide more details about your issue? Are you working with an empty Git Repository and you are trying to push the entities from a ThingWorx file repository? First I would advise you to invoke the Pull service of your Git Backup Thing, then add your entities in the file repository and then perform the push.

**Comment by cbadici** [comment]
Since no response was provided in this thread and this functionality was already validated on ThingWorx 9.0, the issue will be closed
