### ISSUE TITLE
Add functionality to export one/more tags belonging to a project

### ISSUE THREAD

**Issue by ricvec** [PTCInc/thingworx-gitbackup-extension#24]
I am requesting the possibility to export some subset of a project identified by tags.
I have done that and the preview is in the following picture.
![2021-09-17_10-14-50](https://user-images.githubusercontent.com/48289301/133748929-6d22523e-14a3-4126-9765-4b65cad75da0.png)

**Comment by vrosu** [comment]
enhancement released as part of Extension version 5.0.0
