### ISSUE TITLE
Add functionality to exclude folders from the "git status" page

### ISSUE THREAD

**Issue by ricvec** [PTCInc/thingworx-gitbackup-extension#25]
I am requesting this improvement because I have one repository for Thingworx application and for the Eclipse workspace of extensions.
Whenever I am aligning the project from the mashups, the file for the workspace are always considered as "modified" and I cannot skipped those files/folder from the comparison

**Comment by vrosu** [comment]
The Extension is not meant to handle Eclipse workspaces, as explained in the user guide. I do agree the functionality would be nice to have, but it would add more complexity (as we need both GUI to handle the exclude folders and services). I don't plan to do this for now, but in case anyone has a need for this, I would be happy to explain how to do that.
