### ISSUE TITLE
If i Push the entities it'll only getting pushed in File Repository and not in Git Repository. Thingworx version -9.2.3

### ISSUE THREAD

**Issue by anitas4** [PTCInc/thingworx-gitbackup-extension#28]
Logs - 
-Error [authenticating connection], Server websocket will be closed. cause: Missing application key!
- Execution error in service script [QueryStatus] :: Missing unknown 0000000000000000000000000000000000000000
-  **Git Push Issue**
- org.eclipse.jgit.api.errors.TransportException: https://github.com/xyz/xyzRepository.git: not authorized_ at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:147)_ at gb.GitBackupTemplate.Push(GitBackupTemplate.java:244)_ at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)_ at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)_ at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)_ at java.base/java.lang.reflect.Method.invoke(Method.java:566)_ at com.thingworx.common.processors.ReflectionProcessor.processService(ReflectionProcessor.java:230)_ at com.thingworx.handlers.ReflectionServiceHandler.processService(ReflectionServiceHandler.java:50)_ at com.thingworx.handlers.ServiceHandlerBase.processServiceWithMetrics(ServiceHandlerBase.java:48)_ at

**Comment by anitas4** [comment]
Can anyone reply?

**Comment by cbadici** [comment]
Hi, 
This looks to me like an authorization issue related to your Git repository. Have you properly configured your Git Backup Thing? Please describe the steps you performed so I can try to reproduce your issue.

**Comment by anitas4** [comment]
![image](https://user-images.githubusercontent.com/30861388/140718897-26f3a934-6416-40c3-acb1-276c5ae72d0b.png)
![image](https://user-images.githubusercontent.com/30861388/140718971-02479d31-b3b2-44ac-a8fa-349c70ce4dcb.png)
Referred the Guide and configured same.

**Comment by cbadici** [comment]
Connectivity to a variety of Git repositories has been previously verified and it works as expected. I notice that your error is related to permissions for a GitHub repository. 
Did you set up your personal access token in GitHub and used it in the Password field in your Git Backup thing's configuration table?

**Comment by anitas4** [comment]
yes, added PAT and tried still getting error.

org.eclipse.jgit.api.errors.TransportException: https://github.com/xyz/xyz.git: error occurred during unpacking on the remote end: index-pack abnormal exit_ at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:147)_ at gb.GitBackupTemplate.Push(GitBackupTemplate.java:244)_ at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)_ at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)_ at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)_ at java.base/java.lang.reflect.Method.invoke(Method.java:566)_ at

**Comment by cbadici** [comment]
This error is related to the fact that the git client cannot write to the remote repository because either permissions are missing or the capacity is full. I assume it is related to missing permissions since the remote repository would be empty right now. Did you assign all the permissions when you created the PAT? Just edit the token and check all the boxes for the permissions.

**Comment by anitas4** [comment]
i have given all the permissions to PAT  and my repo is also empty

**Comment by anitas4** [comment]
Please reply

**Comment by anitas4** [comment]
access issue resolved but not able to push into another branch other than 'master', if try to push to another branch it is getting added in master branch only.

**Comment by anitas4** [comment]
Can someone reply?

**Comment by stefan-lacatus** [comment]
What repository are you pushing to? Is it literally `https://github.com/xyz/xyz.git`? Do you have access to it?

**Comment by anitas4** [comment]
I am pushing into my personal repo and this is just demo repo link i have given, and yes i have access.
Not able to push into another branch is related to Access issue?

**Comment by anitas4** [comment]
any suggestions?

**Comment by cbadici** [comment]
@anitas4 Have you managed to push your entities on a different branch? I have tested the Git extension on multiple branches and I have no issues. You need to first create your remote branch, pull the repository. Then in the Mashup you select your remote branch (a local branch will be automatically created for you). You can check it out, you add your content/or remove content and then you push it. The commit info will show that you have pushed the content on your respective branch. let me know if this has worked for you. The same can be done just with services, by switching the branch in the Git configuration table.

**Comment by ksmbasha1** [comment]
when I am trying to push the files in GIT, I a getting this error
org.eclipse.jgit.api.errors.TransportException: https://github.com/ksmbasha11/repo101.git: not authorized__ at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:147)__ at gb.GitBackupTemplate.Push(GitBackupTemplate.java:243)__ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)__ at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)__ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)__ at java.lang.reflect.Method.invoke(Method.java:498)__ at com.thingworx.common.processors.ReflectionProcessor.processService(ReflectionProcessor.java:261)__ at com.thingworx.handlers.ReflectionServiceHandler.processService(ReflectionServiceHandler.java:50)__ at com.thingworx.handlers.ServiceHandlerBase.processServiceWithMetrics(ServiceHandlerBase.java:48)__ at com.thingworx.things.Thing.processServiceRequestDirect(Thing.java:8248)__ at com.thingworx.things.Thing.processAPIServiceRequest(Thing.java:8186)__ at com.thingworx.webservices.BaseService.handleInvoke(BaseService.java:3220)__ at com.thingworx.webservices.BaseService.service(BaseService.java:491)__ at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at com.thingworx.security.contenttype.ContentTypeFilter.doFilter(ContentTypeFilter.java:138)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at com.thingworx.security.filter.ValidationFilter.doFilter(ValidationFilter.java:22)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at com.thingworx.security.authentication.AuthenticationFilter.propagateRequest(AuthenticationFilter.java:541)__ at com.thingworx.security.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:210)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)__ at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)__ at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)__ at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at com.thingworx.security.filter.ClickjackFilter.doFilter(ClickjackFilter.java:178)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at com.thingworx.security.filter.ProhibitIfNotLeaderFilter.doFilter(ProhibitIfNotLeaderFilter.java:120)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at com.thingworx.security.filter.HttpResponseHeadersFilter.doFilter(HttpResponseHeadersFilter.java:173)__ at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)__ at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)__ at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)__ at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)__ at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)__ at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)__ at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)__ at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)__ at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)__ at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)__ at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)__ at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)__ at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)__ at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)__ at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)__ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)__ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)__ at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)__ at java.lang.Thread.run(Thread.java:745)__Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/ksmbasha11/repo101.git: not authorized__ at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:540)__ at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:436)__ at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:127)__ at org.eclipse.jgit.transport.Transport.push(Transport.java:1335)__ at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:137)__ ... 60 more__

**Comment by ksmbasha1** [comment]
No Entities are showing
![image](https://user-images.githubusercontent.com/56018676/180605664-65606dd6-4ba5-4034-a638-36928e85a60a.png)

**Comment by ksmbasha1** [comment]
> access issue resolved but not able to push into another branch other than 'master', if try to push to another branch it is getting added in master branch only.

can you help me on access isssue, i am having still that issue.

**Comment by vrosu** [comment]
In case you have new problems, please open a new issue.
One issue in Github must belong to a single issue, not to be reused for multiple ones.
