### ISSUE TITLE
No error message if the repo entity name already exists

### ISSUE THREAD

**Issue by Vonken** [PTCInc/thingworx-gitbackup-extension#29]
When adding a new repo from the mashup "GitBackup.Main.Mashup" there was no error message efter completing the form and no repo was created. Looking in the ThingWorx log after some tries I found this message: "Execution error in service script [AddNewRepo] :: Thing [xxxxx] already exists". Please add an error message if this is the case and keep the form open.

**Comment by cbadici** [comment]
Hello, I would like to clarify the issue. Do you mean that a Git Backup Thing was previously created and if you try to create the same thing again (with the same name), from the Mashup you don't get any error message that the Thing already exists? If this is the case, I don't think there is any verification for the Thing name you provide to your Git Backup Thing in the Mashup. An additional service would need to be added to the Mashup to verify if the thing name is unique, prior to moving to the next screen. Of course, you can create your GitBackup thing in the Composer, and in this situation, you can avoid duplicate names.

**Comment by vrosu** [comment]
Enhancement released as part of Extension version 5.0.0 #
