### ISSUE TITLE
Instead of Entities, only services can be pushed ?

### ISSUE THREAD

**Issue by psp316r** [PTCInc/thingworx-gitbackup-extension#30]
Need to push only services, not total entites.

Can it be done ?

Thanks,
Shashi.

**Comment by vrosu** [comment]
Git technology works with files only. The GitBackup Extension works with Entity Export files which contain the full Entity, not just services. If you want to push services, you need to modify the extension to extract the services as files (by parsing the XML). As far as I am aware, we do not plan for this functionality (@cbadici please confirm). 
Feel free to fork the extension to add this functionality.

**Comment by cbadici** [comment]
I agree with what @vrosu has mentioned. So basically with the Git Extension, you may push whatever files you have in a ThingWorx repository to your remote Git repository. However, from ThingWorx you can export entities, not the services that are related to your entities. Therefore, you will need a new extension that allows you to export only the services (and here you can expand our Git extension or create your own extension for this).
