### ISSUE TITLE
Thingworx GitHub Extension

### ISSUE THREAD

**Issue by AbinayaPonnusamy** [PTCInc/thingworx-gitbackup-extension#32]
Can we committ only service to gitrepository instead of one Thing?

**Comment by cbadici** [comment]
Hi @AbinayaPonnusamy , there was already a question asked for this recently, please also check https://github.com/PTCInc/thingworx-gitbackup-extension/issues/30 . With the Git extension you can commit any files you have in your ThingWorx repository to your Git Repository. However, from ThingWorx, you cannot export only services, but entities. To extract only the services from a Thing's definition, you would need a new extension to parse the XML and just output the services.
