### ISSUE TITLE
Errors while exporting

### ISSUE THREAD

**Issue by AbinayaPonnusamy** [PTCInc/thingworx-gitbackup-extension#34]
I clicked on this export button in mashup - GitBackup.Main.Mashup. Execution failed and errors were observed. 
->Invalid service name: ExportProjectEntities
->Invalid service name: GetConfiguration
What is the problem here

**Comment by cbadici** [comment]
Could you let me know the exact steps you have performed for the export? I have also tested the export in 9.2 using the Git extension and the Export button and it worked well for me.
