### ISSUE TITLE
Github Extension Import Issue

### ISSUE THREAD

**Issue by psp316r** [PTCInc/thingworx-gitbackup-extension#36]
Downloaded the "Git Backup Extension 2.0" from the following :
![image](https://user-images.githubusercontent.com/42883804/166308078-a51115e7-14e6-479c-b991-a01564c88ec4.png)
But I get the following error when Importing: 
```shell
Extension Exception: A write error occurred while copying package for processing.
 ```
The TWX version I am using is ThingWorx 9.2.4-b254.
 
Thanks,
Shashi.

**Comment by vrosu** [comment]
Hi @psp316r. 
I just imported the extension in ThingWorx 9.3.1 successfully. 
1. What is the exact filename you tried to import?
2. Do you have enough free disk space on your ThingWorxStorage disk?
3. If you look in the ApplicationLog can you see more error details around that moment and statement?

**Comment by psp316r** [comment]
Hi @vrosu ,

1. This is the file name GitBackupExtensionPackforThingWorx90.zip, which I tried to import.
2. Yes there is free space.
3. That's the statement I have in the Application Log

**Comment by vrosu** [comment]
In the platform-settings.json, can you please check that all entries for the Extension import and let us know their values?
Just copy paste that section.

**Comment by vrosu** [comment]
@psp316r , is this issue actual or did you manage to solve it?

**Comment by psp316r** [comment]
Hi @vrosu ,

This issue is resolved by modifying the Extension code in the platform-settings.json

Thanks,
Shashi.
