### ISSUE TITLE
GUI Mashup is not working on TWX 9.3.0 and question on HA compatibility

### ISSUE THREAD

**Issue by vamsikoppuravuri-git** [PTCInc/thingworx-gitbackup-extension#39]
Hi, we are trying to use this extension on TWX 9.3.0 but the UI is not working as intended. No buttons are working but services are working fine. Do you see any compatibility issues here. Another question here is that while importing into HA environment, I can see the warnings that it's not compatible with HA environment. This is just because the extn metadata files are not having the HA flag or this extn is not tested in HA environment? Can you please clarify. Thanks.

**Comment by vrosu** [comment]
Hi @vamsikoppuravuri-git ,
While I can not comment exactly about ThingWorx 9.3.0, I tested the extension in ThingWorx 9.3.3 and Firefox 103.0.2 and it worked fine. 
By that I mean I was able to:
- add a GitHub repository
- execute pull
- modify some files (delete one, modify another)
- pushed the commit to the online repo
I expect that either in your situation there's an error which you should be able to diagnose easy enough if you open the developer tools when clicking the buttons in the mashup, or you modified by accident something in the main mashup.
Regarding HA, that was not tested at all in HA - simply said I never even had access to an HA cluster to test it into.

**Comment by vrosu** [comment]
Hi @vamsikoppuravuri-git,

Did you manage to solve your issue by following the advice I shared above? 
Please let me know if I can help you in any other way.
