### ISSUE TITLE
Error when trying to view GIT thing

### ISSUE THREAD

**Issue by krishnakomal** [PTCInc/thingworx-gitbackup-extension#41]
Hi,

 I am trying to pull from GIT repo to thingworx repo.But I am unable to execute any services on GITTHING created using mashup.Please check below mashup screen.

![KN_9954684_0-1669108396807](https://user-images.githubusercontent.com/30370427/204757563-2d07cee7-10c0-4dc2-8ed2-0ce0552a20be.png)

The error in Application logs is Thing [TestGitThing] is not running.Tried restarting the thing and disabling/enabling thing.But still its not working.I am connecting from http thingworx instance to GIT url which is in https.Let me know if it causes the issue

**Comment by vrosu** [comment]
Hi @krishnakomal,
Please activate the Stack Strace error logging in the Logging Subsystem and look in the ErrorLog file when this error happens. Let us know the specific line where the code fails. Have you checked if the Certification Authority that signs the git HTTPS endpoint is present in the JVM trust store?
