### ISSUE TITLE
Best Practices for Git Backup Extension

### ISSUE THREAD

**Issue by psp316r** [PTCInc/thingworx-gitbackup-extension#42]
Hello,

Is there any best practice documentation for GitBackup Extension?

Thanks,
Shashi Preetham.

**Comment by vrosu** [comment]
Hi,
There's a detailed section dedicated to use-cases in the User Guide. Another important point, and mentioned in the Known Limitations in the same user guide, is that this Extension is not intended to provide a full replacement for a Git client.
I will say proactively, in case it applies, that Git best practices are assumed to be known by the end-user.
In this context, what kind of best practices you refer to?
