### ISSUE TITLE
Difference in entity XML

### ISSUE THREAD

**Issue by JensCarmbrant** [PTCInc/thingworx-gitbackup-extension#46]
Hello,

I have noticed that there is a difference between the XML's when using the GitBackup extension and when using the built in "Export as source control" functionality of the TWX platform and then using other Git tools for source control.

There is an XML tag in the "Entities" element named "universal".
This tag contains "password" when someone uses the GitBackup extension, but is empty when exported using the export as source control function.

This causes some headache when later trying to see what differences has been made in the code.

Hope this can be fixed in some way. For now the only option I can see is to use some tool to add the "password" for anyone not using the GitBackup extension.

Thanks,
Jens

**Comment by vrosu** [comment]
Hi Jens,
I tested now the GitHub Extension in ThingWorx 9.3.8. I observed that if I export entities using the Export functionality from the GitBackup Main Mashup the universal = password is there. 
However, the same attribute is there if I click in ThingWorx Composer "Export to Source Control" from the upper drop down list seen at each entity next to Save, Cancel etc.
Can you let me know the details around the functionality you call where you don't see the attribute?

**Comment by JensCarmbrant** [comment]
Hello,

You are correct. It seems like the universal = password is there when exporting as source control manually for each entity. I also just tested in my 9.3.5 platform.

The issue then seems to be when exporting a whole project(?) using the exporting function, like this:

![image](https://user-images.githubusercontent.com/123723246/234201392-d4ae2055-5a84-4ed7-b046-2131c713e162.png)

If you could try that as well and see, I think it will be the same issue for you.

**Comment by vrosu** [comment]
And out of curiosity, can you test this behavior in 9.3.8 let's say?

**Comment by JensCarmbrant** [comment]
The universal tag was empty for my colleague as well.
This leads me to believe there could be some platform setting or something that is causing this...

Do you think I should open a case with PTC?

**Comment by vrosu** [comment]
Yes, I think that would be the next step.
Considering what I see here I think it won't be extremely fast to solve, because effectively we either need a way to reproduce internally, or to gather enough logs to understand what happening.
But yes, that's the best way to handle this as of now. Once it's solved, make sure please to comment here for others benefit.

**Comment by JensCarmbrant** [comment]
In the end it seems like there is a bug in the export function when also zipping the project.
So this should not have anything to do with the GitBackup extension.
