### ISSUE TITLE
v5 Cannot Create New Repo - New GitThing

### ISSUE THREAD

**Issue by ilacurcu** [PTCInc/thingworx-gitbackup-extension#48]
With the latest version I cannot create new GitThing because the _AddNewRepo_ service has a problem, "The configuration table structure does not match"
![image](https://github.com/PTCInc/thingworx-gitbackup-extension/assets/31687090/a71817ac-c05e-45e0-af45-e940700366d4)

![image](https://github.com/PTCInc/thingworx-gitbackup-extension/assets/31687090/5ba1ba9e-0370-4401-a97e-6b131001cfc1)

![image](https://github.com/PTCInc/thingworx-gitbackup-extension/assets/31687090/77b357ef-7652-40f8-aa15-b8c5bc01f0f6)

**Comment by vrosu** [comment]
Hi @ilacurcu,
Can you install this version below (after removing fully version 5.0.0) and see if this happens again?
[GitBackupExtensionPack.zip](https://github.com/PTCInc/thingworx-gitbackup-extension/files/11597517/GitBackupExtensionPack.zip)

**Comment by vrosu** [comment]
Hi @ilacurcu ,
From my end, I installed the v 5.0.0 version and I was able to create a new repository from the Mashup without errors. I found it strange it succeeded on my end, and in order to validate this, can you please share the reproduction steps, as granular as you can?

**Comment by vrosu** [comment]
Closing as not reproducible.
