### ISSUE TITLE
Resources_ExtensionsExport, Things_ExtensionImportTargets  no longer exists.

### ISSUE THREAD

**Issue by pshashipreetham** [PTCInc/thingworx-gitbackup-extension#50]
Hi @vrosu,

I just faced the below error when I opened GitBackup.Main.Mashup:
![image](https://github.com/PTCInc/thingworx-gitbackup-extension/assets/42883804/73bbc5e1-cf4e-4d00-aa72-b6c013b6bcb9)

Thanks,
Shashi Preetham.

**Comment by vrosu** [comment]
Hi @pshashipreetham ,
Can you please add the exact steps you performed before reaching this error?
I verified now, and this issue does not appear in a 9.4.0 ThingWorx installation.
(I'm assuming you read the documentation and you know that the GitBackup extension is an extension pack, and that you also verified that all extensions are present and installed)

**Comment by vrosu** [comment]
@pshashipreetham Can you please either reply to my question or let me know if you managed to solve this issue on your own (and if yes, what was really the issue)? 
Thanks !

**Comment by pshashipreetham** [comment]
Hi @vrosu,

Apologies for the delayed response missed your last comment.

Looks like I made changes in the Last Version Couple of years ago when re-imported the latest version caused this issue, Extension is GOOD.
