### ISSUE TITLE
No case for group in ExportProjectEntities

### ISSUE THREAD

**Issue by msheridanTSM** [PTCInc/thingworx-gitbackup-extension#52]
GitBackup Extension version 5.0.0 on ThingWorx 9.3.7, entities of the type "Group" do not get exported when using the entity picker. I had a look at the code and I was able to fix this by including a "Group" case in the ExportProjectEntities service in Git.Utility.ThingShape.

**Comment by vrosu** [comment]
Thanks for reporting this, I'll mark it as a bug and fix it in the future.

**Comment by vrosu** [comment]
@msheridanTSM while fixing this, I observed that the same applied for "ThingGroup" and fixed that as well.
  `case "ThingGroup":`

**Comment by vrosu** [comment]
@msheridanTSM fixed in [5.0.1 release](https://github.com/PTCInc/thingworx-gitbackup-extension/releases/tag/V5.0.1-9.3)
