### ISSUE TITLE
Working with two independent repositories on the same server

### ISSUE THREAD

**Issue by vrabie-d** [PTCInc/thingworx-gitbackup-extension#54]
I have two separate projects that I want to keep track of on the same ThingWorx server. I created two independent repos, however I cannot switch between them in GitBackup. If I want to push changes to Repo2, files from Repo1 will also be committed despite me not adding them in the Export step. Is there anything I am missing or might be doing wrong?

- GitBackup 5.0.0
- ThingWorx 9.3.6

**Comment by vrosu** [comment]
Can you check in the Git Thing's configuration and let me know what is the FileRepository folder you specified for each Thing?

**Comment by vrabie-d** [comment]
I noticed the issue, by accident both Things had the same path for FileRepository. Changed that and now there are no more issues
