### ISSUE TITLE
Export project dependants does not work

### ISSUE THREAD

**Issue by niklaseisenhuth** [PTCInc/thingworx-gitbackup-extension#57]
When I select a project to export it into the workspace, I select the checkbox to also include the project dependants. 
I would expect, that also the projects which are dependant and its entities will be exported but this is not the case.

In the documentation, I could not find any information about what this checkbox exactly does. Is there a possibility to export all dependant projects at once?

![Screenshot 2024-04-03 at 14 41 38](https://github.com/PTCInc/thingworx-gitbackup-extension/assets/78529616/287dbd0c-c81f-4250-979c-ecf6e57fbc93)
![Screenshot 2024-04-03 at 14 39 47](https://github.com/PTCInc/thingworx-gitbackup-extension/assets/78529616/75b8aef5-7615-467b-9e4c-49e4cbe0e8d5)

**Comment by vrosu** [comment]
Hi @niklaseisenhuth
This was unfortunately a missed test case when adding the new UI that allows granular entity export capabilities.
The fix involves displaying the entities from ALL other dependent projects in the EntityPicker mashup, if the user checks the "Include Dependents" checkbox.

**Comment by vrosu** [comment]
@niklaseisenhuth fixed in [5.0.1 release](https://github.com/PTCInc/thingworx-gitbackup-extension/releases/tag/V5.0.1-9.3)
