### ISSUE TITLE
Mashup freezes and connectino to github is not established

### ISSUE THREAD

**Issue by LeonardMichalas** [PTCInc/thingworx-gitbackup-extension#9]
I am currently facing the issue that the GitBackup.Master mashup freezes when it tries to connect to a GitThing I created based on the GitBackupTemplate. 

I step by step followed the instructions of this document: https://github.com/PTCInc/thingworx-gitbackup-extension/releases/download/V4.1.0-9.0/Git.Backup.Extension.User.Guide.v4.1.0.pdf

Unfortunatly all log files in ThingworxStorage/logs are empty. 

Anyone else facing the issue? Any ideas how I can further debug the issue? 

![image](https://user-images.githubusercontent.com/22077655/95748057-f6c31e00-0c88-11eb-80a5-cd23c8546dd9.png)

**Comment by vrosu** [comment]
What ThingWorx version are you using?

**Comment by LeonardMichalas** [comment]
@vrosu Thank you for the fast response. I am using ThingWorx 9.0.2-b136

**Comment by vrosu** [comment]
Browser?

**Comment by LeonardMichalas** [comment]
Google Chrome Version 86.0.4240.75 (Official Build) (64-Bit)

**Comment by vrosu** [comment]
I've tested now with Chrome Version 85.0.4183.102 (Official Build) (64-bit), and the same ThingWorx version you are using and the Pull worked fine. Not a chance to use the 86 Chrome due to IT policy :( 
Before doing the next step, can you confirm the same happens with Firefox?
Can you reply with your (as anonymized as possible) configuration parameters you are using?

**Comment by LeonardMichalas** [comment]
I entered the following information to the GitThing setup wizzard: 

Git Thing Name: ProjectNameGitThing

Git Username: LeonardMichalas (my git username)
Git account password: A personal access token I created
Git server type: Other (As I am using Github)

Comitter Name: LeonardMichalas
Committ email: leonard.michalas@outlook.com (publicly available, I also tested with <username>@users.noreply.github.com

Git Repo URI: https://github.com/LeonardMichalas/ProjectName
File Repository: GitRepository

Localization token prefix: <empty>
File repository path: /
Initial branch: Master

No Proxy usage required. 

--

Issue also occurs on Firefox Browser with version 81.0.1 (64-Bit)

--

Network traffic: 
![image](https://user-images.githubusercontent.com/22077655/95750812-33911400-0c8d-11eb-9169-eef2cc2ad80c.png)
Console log: 
![image](https://user-images.githubusercontent.com/22077655/95750874-4b689800-0c8d-11eb-99cf-429b444bc5cd.png)

The console error appeared when I copy pasted my github repository URI to the setup wizzard.

**Comment by vrosu** [comment]
ah - can you use a File repository path:  that includes a string in addition to "/" ? There should be a small example in that text box, something like : /myverybrandnewfolder ;)

**Comment by LeonardMichalas** [comment]
@vrosu Really appreciate your support. 

After changing the File Repository path from "/" to "/ThingworxEntities" the page is not frozen anymore and I was able to select all entities I would like to push to my repository. 

However after I pushed my changes, nothing ends up in the repository, eventhough I do not get an error message on the Mashup.

**Comment by vrosu** [comment]
Np. If it's fine for you, I will close this issue, since that's solved, and ask you to open a new issue for the latest issue?
I'm a fan of keeping stuff organized.

**Comment by bensafran** [comment]
I had exactly the same issue. Changing the path solved it. Perhaps it needs to be said somewhere that you can't, in fact, use the root of the repo as a folder.
